_target_: dataset.mask.DirectoryImageWithMaskDataset
image_path: "datasets/casiagait_b_video90/train/"
mask_image_path: "datasets/casiagait_b_video90/mask_train/"

ground_truthes_detection_path: "datasets/casiagait_b_video90/detect_train/"
