_target_: dataset.train_background.TrainBackGroundDataset
face_path: "datasets/casia/test_face_moving/face/"
mask_path: "datasets/casia/test_face_moving/mask/"
detection_path: "datasets/casia/test_face_moving/detection/"
