_target_: dataset.train_background.TrainBackGroundDataset
face_path: "datasets/casia_front/test/face/"
mask_path: "datasets/casia_front/test/mask/"
detection_path: "datasets/casia_front/test/detection/"
