_target_: dataset.train_background.TrainBackGroundDataset
face_path: "datasets/faceforensics_pp/train/face/"
mask_path: "datasets/faceforensics_pp/train/mask/"
detection_path: "datasets/faceforensics_pp/train/detection/"
