defaults:
  - model: s3fd # 使用モデルの設定
  - dataset: casia_test # 使用データセットの設定

path: ""
output_dir: ${hydra:runtime.output_dir}

dataset:
  max_iter: 3000
  _partial_: True

main:
  trainer:
    _target_: ${model.trainer}
    dataset_factory: ${dataset}
    model_conf: ${model}
  image_num: 40
  adv_bg_image_path: ${path}
  dataset: ${dataset}
  save_detection:
    adv_bg_image_path: ${main.adv_bg_image_path}
    gt_det_save_dir: "ground_truth_detection/"
    adv_bg_det_save_dir: "adversarial_background_detection/"
  tbx_monitor:
    class_names_path: ${dataset.class_names}
    output_dir: ${hydra:runtime.output_dir}
  evaluate_background:
    model_thresh: 0.6
    output_dir: ${output_dir}
