hydra:
  callbacks:
    git_logging:
      _target_: util.callback.GitCallback
# プロジェクト全体で用いる設定
defaults:
  - model: s3fd # 使用モデルの設定
  - dataset@monitor_dataset: casia_mini # 使用データセットの設定
  - dataset@evaluate_dataset: casia_train # 使用データセットの設定
  - patch_manager: tiling_background
  - _self_

# output file on this directory
output_dir: ${hydra:runtime.output_dir}
iou_threshold: 0.5

# 実行モード指定
mode: "monitor"

# _partial_ be dataset factory
monitor_dataset:
  max_iter: 300
  _partial_: true
evaluate_dataset:
  max_iter: 3000
  _partial_: true

# 敵対的画像生成時の設定
#  model: ${model}
# 動作確認時。tensorboardで画像も記録する
monitor_trainer:
  _target_: ${model.trainer}
  dataset_factory: ${monitor_dataset}
  model_conf: ${model}
# 学習時。画像を記録しない
evaluate_trainer:
  _target_: ${model.trainer}
  dataset_factory: ${evaluate_dataset}
  model_conf: ${model}

# 敵対的画像生成時の設定
train_adversarial_image:
  max_epoch: 300 # 一枚の画像ごとに摂動を加える最大回数
  loss: ${loss}
  model_thresh: 0.6
  output_dir: ${output_dir}
loss:
  tpc_weight: 0.2
  tps_weight: 1
  fpc_weight: 1
  tv_weight: 0.1
  calc_z: # 損失計算に必要なパラメータ計算の設定
    iou_threshold: ${iou_threshold} # 値が閾値以上であるか判定する
