# プロジェクト全体で用いる設定
defaults:
  - model: s3fd # 使用モデルの設定
  - dataset@monitor_dataset: gait_test1 # 使用データセットの設定
  - dataset@evaluate_dataset:  casia_gait_b # 使用データセットの設定
output_dir: ${hydra:runtime.output_dir}
iou_threshold: 0.5
n_b: 3 # クラスタリングしたグループ毎に割り当てられるパッチの枚数
mode: "monitor"

train_main: # 敵対的画像生成時の設定
  mode: ${mode}
  output_dir: ${output_dir}
  model: ${model}
  monitor_mode:
    dataset: ${monitor_dataset}
  evaluate_mode:
    dataset: ${evaluate_dataset}
  train_adversarial_image: # 敵対的画像生成時の設定
    max_epoch: 300 # 一枚の画像ごとに摂動を加える最大回数
    loss: ${train_main.loss}
    model_thresh: 0.6
  loss:
    tpc_weight: 0.2
    tps_weight: 1
    fpc_weight: 1
    tv_weight: 0.1
    calc_z: # 損失計算に必要なパラメータ計算の設定
      iou_threshold: ${iou_threshold} # 値が閾値以上であるか判定する
