hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

# プロジェクト全体で用いる設定
defaults:
  - loss:
    - confidence_gradiation_fpc
  - model: s3fd # 使用モデルの設定
  - dataset@monitor_dataset: casia_mini # 使用データセットの設定
  - dataset@evaluate_dataset: faceforensics_pp_train # 使用データセットの設定
  - ptmanager: tiling_scalable
  - optim: ni_fgsm
  - _self_
  - override hydra/sweeper: optuna

# output file on this directory
output_dir: ${hydra:runtime.output_dir}
iou_threshold: 0.5

# 実行モード指定
mode: "monitor"

# _partial_ be dataset factory
monitor_dataset:
  max_iter: 30
  _partial_: true
evaluate_dataset:
  max_iter: 3000
  _partial_: true

# 敵対的画像生成時の設定
#  model: ${model}
# 動作確認時。tensorboardで画像も記録する
monitor_trainer:
  _target_: ${model.trainer}
  dataset_factory: ${monitor_dataset}
  model_conf: ${model}
# 学習時。画像を記録しない
evaluate_trainer:
  _target_: ${model.trainer}
  dataset_factory: ${evaluate_dataset}
  model_conf: ${model}

# 敵対的画像生成時の設定
train_parameters:
  max_epoch: 150 # 一枚の画像ごとに摂動を加える最大回数
  # loss: ${loss}
  model_thresh: 0.6
  output_dir: ${output_dir}
