
borderline_fpc:
  func:
    _target_: "loss.confidence_gradiation.BorderlineFPCLoss"
    normalize: True
    theta_F: 0.3
    theta_T: 0.9
  weight: 1
  use_all_targets: False

borderline_num:
  func:
    _target_: "loss.confidence_gradiation.BorderlineNumberLoss"
    theta_F: 0.3
    theta_T: 0.9
  weight: 0.1
  use_all_targets: False
